// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.27.2
// source: configuration.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

const protobufPackage = 'configuration';

export interface Validations {
  zeroFundBalance: string;
  minSIPAmount: string;
}

export interface PaymentGateway {
  link: string;
  name: string;
}

export interface Config {
  amcCode: string;
  validations: Validations[];
  paymentGateway: PaymentGateway[];
}

export interface Configuration {
  pk: string;
  sk: string;
  config: Config[];
}

interface Empty {}

export interface HealthCheckResponse {
  data: string;
}

export interface RetrieveConfigRequest {
  serviceName: string;
  key: string;
}

export interface RetrieveConfigRequests {
  keys: string[];
}

export interface Secret {
  key: string;
  value: string;
}

export interface TenantParamConfig {
  tenant?: Configuration | undefined;
  parameters?: Secret[];
}

export interface RetrieveConfigResponse {
  data: TenantParamConfig | undefined;
}

export interface RetrieveConfigResponses {
  data: { [key: string]: string };
}

export interface RetrieveConfigResponses_DataEntry {
  key: string;
  value: string;
}

export const CONFIGURATION_PACKAGE_NAME = 'configuration';

export interface ConfigServiceClient {
  healthCheck(request: Empty): Observable<HealthCheckResponse>;

  retrieveConfig(request: RetrieveConfigRequest): Observable<RetrieveConfigResponse>;

  retrieveConfigs(request: RetrieveConfigRequests): Observable<RetrieveConfigResponses>;

  refreshConfig(request: Empty): Observable<Empty>;
}

export interface ConfigServiceController {
  healthCheck(
    request: Empty,
  ): Promise<HealthCheckResponse> | Observable<HealthCheckResponse> | HealthCheckResponse;

  retrieveConfig(
    request: RetrieveConfigRequest,
  ): Promise<RetrieveConfigResponse> | Observable<RetrieveConfigResponse> | RetrieveConfigResponse;

  retrieveConfigs(
    request: RetrieveConfigRequests,
  ):
    | Promise<RetrieveConfigResponses>
    | Observable<RetrieveConfigResponses>
    | RetrieveConfigResponses;

  refreshConfig(request: Empty): Promise<Empty> | Observable<Empty> | Empty;
}

export function ConfigServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'healthCheck',
      'retrieveConfig',
      'retrieveConfigs',
      'refreshConfig',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('ConfigService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('ConfigService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CONFIG_SERVICE_NAME = 'ConfigService';
